radiofeed/episodes/urls.py
from django.urls import path

from radiofeed.episodes import views

app_name = "episodes"


urlpatterns = [
    path("new/", views.index, name="index"),
    path("search/episodes/", views.search_episodes, name="search_episodes"),
    path(
        "episodes/<int:episode_id>/<slug:slug>/",
        views.episode_detail,
        name="episode_detail",
    ),
    path(
        "player/start/<int:episode_id>/",
        views.start_player,
        name="start_player",
    ),
    path(
        "player/close/",
        views.close_player,
        name="close_player",
    ),
    path(
        "player/timeupdate/",
        views.player_time_update,
        name="player_time_update",
    ),
    path("history/", views.history, name="history"),
    path(
        "history/<int:episode_id>/remove/",
        views.remove_audio_log,
        name="remove_audio_log",
    ),
    path("bookmarks/", views.bookmarks, name="bookmarks"),
    path(
        "bookmarks/<int:episode_id>/add/",
        views.add_bookmark,
        name="add_bookmark",
    ),
    path(
        "bookmarks/<int:episode_id>/remove/",
        views.remove_bookmark,
        name="remove_bookmark",
    ),
]

radiofeed/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from radiofeed import views

admin.site.site_header = settings.ADMIN_SITE_HEADER


urlpatterns = [
    path("", include("radiofeed.episodes.urls")),
    path("", include("radiofeed.podcasts.urls")),
    path("", include("radiofeed.users.urls")),
    path("account/", include("allauth.urls")),
    path("about/", views.about_page, name="about"),
    path("health-check/", views.health_check, name="health_check"),
    path("accept-cookies/", views.accept_cookies, name="accept_cookies"),
    path("covers/<int:size>/cover.webp", views.cover_image, name="cover_image"),
    path("robots.txt", views.robots, name="robots"),
    path("service-worker.js", views.service_worker, name="service_worker"),
    path("manifest.json", views.manifest, name="manifest"),
    path("favicon.ico", views.favicon, name="favicon"),
    path(".well-known/security.txt", views.security, name="security"),
    path(settings.ADMIN_URL, admin.site.urls),
]

if "django_browser_reload" in settings.INSTALLED_APPS:  # pragma: no cover
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

if "debug_toolbar" in settings.INSTALLED_APPS:  # pragma: no cover
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

radiofeed/episodes/views.py
from datetime import timedelta

from django.contrib import messages
from django.db import IntegrityError
from django.db.models import Exists, OuterRef
from django.http import Http404, HttpRequest, HttpResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.http import require_POST, require_safe

from radiofeed.decorators import require_auth, require_DELETE
from radiofeed.episodes.models import AudioLog, Episode
from radiofeed.htmx import render_htmx
from radiofeed.http import HttpResponseConflict, HttpResponseNoContent
from radiofeed.pagination import render_pagination


@require_safe
@require_auth
def index(request: HttpRequest) -> HttpResponse:
    """List latest episodes from subscriptions if any, else latest episodes from
    promoted podcasts."""
    episodes = (
        Episode.objects.filter(pub_date__gt=timezone.now() - timedelta(days=14))
        .select_related("podcast")
        .order_by("-pub_date", "-id")
    )

    subscribed = episodes.annotate(
        is_subscribed=Exists(
            request.user.subscriptions.filter(podcast=OuterRef("podcast"))
        )
    ).filter(is_subscribed=True)

    has_subscriptions = subscribed.exists()
    promoted = "promoted" in request.GET or not has_subscriptions

    episodes = episodes.filter(podcast__promoted=True) if promoted else subscribed

    return render_pagination(
        request,
        episodes,
        "episodes/index.html",
        {
            "promoted": promoted,
            "has_subscriptions": has_subscriptions,
            "search_url": reverse("episodes:search_episodes"),
        },
    )


@require_safe
@require_auth
def search_episodes(request: HttpRequest) -> HttpResponse:
    """Search episodes. If search empty redirects to index page."""
    if request.search:
        episodes = (
            Episode.objects.search(request.search.value)
            .filter(podcast__private__isnull=False)
            .select_related("podcast")
            .order_by("-rank", "-pub_date")
        )
        return render_pagination(request, episodes, "episodes/search.html")
    return redirect("episodes:index")


@require_safe
@require_auth
def episode_detail(
    request: HttpRequest, episode_id: int, slug: str | None = None
) -> HttpResponse:
    """Renders episode detail."""
    episode = get_object_or_404(
        Episode.objects.select_related("podcast"),
        pk=episode_id,
    )
    return _render_episode_detail(
        request,
        episode,
        {
            "audio_log": request.user.audio_logs.filter(episode=episode).first(),
            "is_bookmarked": request.user.bookmarks.filter(episode=episode).exists(),
            "is_playing": request.player.has(episode.pk),
        },
    )


@require_POST
@require_auth
def start_player(request: HttpRequest, episode_id: int) -> HttpResponse:
    """Starts player. Creates new audio log if required."""
    episode = get_object_or_404(
        Episode.objects.select_related("podcast"),
        pk=episode_id,
    )

    audio_log, _ = request.user.audio_logs.update_or_create(
        episode=episode,
        defaults={
            "listened": timezone.now(),
        },
    )

    request.player.set(episode.pk)

    return _render_audio_player_button(request, audio_log, is_playing=True)


@require_POST
@require_auth
def close_player(request: HttpRequest) -> HttpResponse:
    """Closes audio player."""
    if episode_id := request.player.pop():
        audio_log = get_object_or_404(
            request.user.audio_logs.select_related("episode"),
            episode__pk=episode_id,
        )
        return _render_audio_player_button(request, audio_log, is_playing=False)

    return HttpResponseNoContent()


@require_POST
@require_auth
def player_time_update(request: HttpRequest) -> HttpResponse:
    """Update current play time of episode.

    Time should be passed in POST as `current_time` integer value.

    Returns:
        HTTP BAD REQUEST if missing/invalid `current_time`, otherwise HTTP NO CONTENT.
    """
    if episode_id := request.player.get():
        try:
            request.user.audio_logs.update_or_create(
                episode=get_object_or_404(Episode, pk=episode_id),
                defaults={
                    "current_time": int(request.POST["current_time"]),
                    "listened": timezone.now(),
                },
            )
        except (KeyError, ValueError):
            return HttpResponseBadRequest()

    return HttpResponseNoContent()


@require_safe
@require_auth
def history(request: HttpRequest) -> HttpResponse:
    """Renders user's listening history. User can also search history."""
    audio_logs = request.user.audio_logs.select_related("episode", "episode__podcast")

    if request.search:
        audio_logs = audio_logs.search(request.search.value).order_by(
            "-rank", "-listened"
        )
    else:
        audio_logs = audio_logs.order_by(
            "-listened" if request.ordering.is_desc else "listened"
        )

    return render_pagination(request, audio_logs, "episodes/history.html")


@require_DELETE
@require_auth
def remove_audio_log(request: HttpRequest, episode_id: int) -> HttpResponse:
    """Removes audio log from user history and returns HTMX snippet."""
    # cannot remove episode if in player
    if request.player.has(episode_id):
        raise Http404

    audio_log = get_object_or_404(
        request.user.audio_logs.select_related("episode"),
        episode__pk=episode_id,
    )

    audio_log.delete()

    messages.info(request, "Removed from History")
    return _render_episode_detail(request, audio_log.episode, partial="audio_log")


@require_safe
@require_auth
def bookmarks(request: HttpRequest) -> HttpResponse:
    """Renders user's bookmarks. User can also search their bookmarks."""
    bookmarks = request.user.bookmarks.select_related("episode", "episode__podcast")

    if request.search:
        bookmarks = bookmarks.search(request.search.value).order_by("-rank", "-created")
    else:
        bookmarks = bookmarks.order_by(
            "-created" if request.ordering.is_desc else "created"
        )

    return render_pagination(request, bookmarks, "episodes/bookmarks.html")


@require_POST
@require_auth
def add_bookmark(request: HttpRequest, episode_id: int) -> HttpResponse:
    """Add episode to bookmarks."""
    episode = get_object_or_404(Episode, pk=episode_id)

    try:
        request.user.bookmarks.create(episode=episode)
    except IntegrityError:
        return HttpResponseConflict()

    messages.success(request, "Added to Bookmarks")

    return _render_bookmark_button(request, episode, is_bookmarked=True)


@require_DELETE
@require_auth
def remove_bookmark(request: HttpRequest, episode_id: int) -> HttpResponse:
    """Remove episode from bookmarks."""
    episode = get_object_or_404(Episode, pk=episode_id)
    request.user.bookmarks.filter(episode=episode).delete()

    messages.info(request, "Removed from Bookmarks")

    return _render_bookmark_button(request, episode, is_bookmarked=False)


def _render_episode_detail(
    request: HttpRequest,
    episode: Episode,
    extra_context: dict | None = None,
    **kwargs,
) -> HttpResponse:
    return render_htmx(
        request,
        "episodes/detail.html",
        {
            "episode": episode,
            **(extra_context or {}),
        },
        **kwargs,
    )


def _render_bookmark_button(
    request: HttpRequest, episode: Episode, *, is_bookmarked: bool
) -> HttpResponse:
    return _render_episode_detail(
        request,
        episode,
        {"is_bookmarked": is_bookmarked},
        partial="bookmark_button",
    )


def _render_audio_player_button(
    request: HttpRequest, audio_log: AudioLog, *, is_playing: bool
) -> HttpResponse:
    return _render_episode_detail(
        request,
        audio_log.episode,
        {
            "audio_log": audio_log,
            "is_playing": is_playing,
            "start_player": is_playing,
        },
        partial="audio_player_button",
    )

templates/episodes/_audio_player.html
{% load heroicons audio_player %}
{% if user.is_authenticated %}
    <div id="audio-player" {% if hx_oob %}hx-swap-oob="true"{% endif %}>
        {% if audio_log and is_playing %}
            {% with episode=audio_log.episode METADATA_TAG="audioplayer-metadata" %}
                {% get_media_metadata episode as metadata %}
                {% if metadata %}{{ metadata|json_script:METADATA_TAG }}{% endif %}
                <div class="h-40 sm:h-28"
                    {# djlint:off #}
                x-data="
                audioPlayer(
                    csrfToken='{{ csrf_token }}',
                    currentTime={{ audio_log.current_time|default:0 }},
                    metadataTag='{{ METADATA_TAG }}',
                    startPlayer={{ start_player|yesno:'true,false' }},
                    timeUpdateUrl='{% url 'episodes:player_time_update' %}',
                )"
                    {# djlint:on #}
                    @keydown.window="shortcuts">
                    <audio x-ref="audio"
                           preload="auto"
                           @loadedmetadata="loaded"
                           @ended="ended"
                           @timeupdate="timeUpdate"
                           @play="play"
                           @pause="pause"
                           @error.prevent="error">
                        <source src="{{ episode.media_url }}" type="{{ episode.media_type }}">
                    </audio>
                    <div class="fixed bottom-0 z-10 w-full p-2 font-semibold text-white opacity-100 bg-gradient-to-b from-violet-900 to-black transform ease-in-out duration-1000 translate-y-0 htmx-added:opacity-0 htmx-added:translate-y-24">
                        <div class="items-center w-full sm:flex space-y-2 sm:space-y-0 divide-y sm:divide-y-0 sm:divide-x divide-solid divide-gray-500">
                            <div class="sm:w-1/2" hx-swap="innerHTML show:window:top">
                                {% with podcast=episode.podcast %}
                                    <div class="flex items-center space-x-2 lg:space-x-3 pr-2">
                                        {% cover_image podcast.cover_url 100 podcast.cleaned_title url=podcast.get_absolute_url css_class="w-16 h-16" %}
                                        <div class="flex flex-col h-16 place-content-between">
                                            <a class="font-bold leading-tight tracking-tight break-words line-clamp-2 hover:text-blue-300"
                                               href="{{ episode.get_absolute_url }}"
                                               aria-label="{{ episode.cleaned_title }}"
                                               title="{{ episode.cleaned_title }}">{{ episode.cleaned_title }}</a>
                                            <a class="text-xs leading-tight tracking-tight truncate w-60 lg:w-96 xl:w-128 md:text-sm hover:text-blue-300"
                                               href="{{ podcast.get_episodes_url }}"
                                               aria-label="{{ podcast.cleaned_title }}: Episodes"
                                               title="{{ podcast.cleaned_title }}: Episodes">{{ podcast.cleaned_title }}
                                            </a>
                                        </div>
                                    </div>
                                {% endwith %}
                            </div>
                            <div class="flex flex-col h-16 sm:w-1/2 place-content-end sm:pl-3 space-y-2 sm:space-y-3">
                                <div class="grid grid-cols-3 place-content-between">
                                    <div x-text="counters.current"
                                         aria-label="Current Time"
                                         title="Current Time"
                                         class="flex items-center justify-start font-mono text-xs md:text-sm"
                                         :class="isPlaying ? '' : 'text-gray-300'"></div>
                                    <div class="flex items-center justify-center opacity-75 animate-pulse space-x-6"
                                         x-show="!isLoaded">Loading...</div>
                                    {% with BUTTON_CSS="focus:outline-none hover:text-blue-300 inline-block" INACTIVE_CSS="opacity-75 cursor-not-allowed pointer-events-none" %}
                                        <div class="flex items-center justify-center space-x-6"
                                             x-show="isLoaded"
                                             x-cloak>
                                            <button aria-label="Skip Back 10 Seconds"
                                                    title="Skip Back 10 Seconds"
                                                    class="{{ BUTTON_CSS }}"
                                                    @click="skipBack"
                                                    :class="isPlaying || '{{ INACTIVE_CSS }}'">
                                                {% heroicon_outline "backward" size=30 %}
                                            </button>
                                            <button aria-label="Play"
                                                    title="Play"
                                                    class="{{ BUTTON_CSS }}"
                                                    @click="togglePlayPause"
                                                    x-show="!isPlaying">
                                                {% heroicon_outline "play-circle" size=36 %}
                                            </button>
                                            <button aria-label="Pause"
                                                    title="Pause"
                                                    class="{{ BUTTON_CSS }}"
                                                    @click="togglePlayPause"
                                                    x-show="isPlaying">
                                                {% heroicon_outline "pause-circle" size=36 %}
                                            </button>
                                            <button aria-label="Skip Forward 10 Seconds"
                                                    title="Skip Forward 10 Seconds"
                                                    class="{{ BUTTON_CSS }}"
                                                    @click="skipForward"
                                                    :class="isPlaying || '{{ INACTIVE_CSS }}'">
                                                {% heroicon_outline "forward" size=30 %}
                                            </button>
                                        </div>
                                    {% endwith %}
                                    <div x-text="counters.remaining"
                                         aria-label="Time Remaining"
                                         title="Time Remaining"
                                         class="flex items-center justify-end font-mono text-xs md:text-sm"
                                         :class="isPlaying ? '' : 'text-gray-300'"></div>
                                </div>
                                <div class="w-full">
                                    <input type="range"
                                           aria-label="Progress"
                                           title="Progress"
                                           min="0"
                                           x-ref="range"
                                           x-model="runtime"
                                           @change="skip"
                                           :max="duration"
                                           :disabled="!isPlaying"
                                           class="flex items-center w-full mx-auto bg-transparent focus:outline-none"
                                           :class="isPlaying ? 'cursor-pointer' : 'cursor-not-allowed'">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endwith %}
        {% endif %}
    </div>
{% endif %}

templates/episodes/_episode.html
{# vim: set filetype=htmldjango #}
{% with podcast=episode.podcast episode_url=episode.get_absolute_url %}
    <article class="flex items-center cursor-pointer group space-x-3"
             role="link"
             hx-get="{{ episode_url }}"
             hx-push-url="true">
        {% with size=100 css_class="h-16 w-16 group-hover:grayscale" %}
            {% if is_podcast_detail %}
                {% cover_image episode.get_cover_url size episode.cleaned_title css_class=css_class %}
            {% else %}
                {% cover_image podcast.cover_url size podcast.cleaned_title css_class=css_class %}
            {% endif %}
        {% endwith %}
        <div class="flex flex-col h-16 place-content-between">
            <h2 class="font-bold leading-tight tracking-tight break-words line-clamp-2"
                aria-label="{{ episode.cleaned_title }}"
                title="{{ episode.cleaned_title }}">
                <a class="link group-hover:text-blue-600 dark:group-hover:text-blue-300"
                   href="{{ episode_url }}">{{ episode.cleaned_title }}</a>
            </h2>
            <h3 class="text-xs font-semibold leading-tight tracking-tight text-gray-600 truncate w-60 sm:w-128 md:text-sm dark:text-gray-300"
                aria-label="{{ podcast.cleaned_title }}"
                title="{{ podcast.cleaned_title }}">
                {% if is_podcast_detail %}
                    {% include "_date.html" with value=episode.pub_date title="Release Date" %}
                {% else %}
                    {{ podcast.cleaned_title|truncatechars:180 }}
                {% endif %}
            </h3>
        </div>
    </article>
{% endwith %}

templates/episodes/_episodes.html
{# vim: set filetype=htmldjango #}
{% if page_obj.paginator.count %}
    {% with has_other_pages=page_obj.has_other_pages %}
        <ul class="divide-y divide-solid" id="{{ pagination_target }}">
            {% if has_other_pages %}
                <li class="pb-3">{% include "_pagination_links.html" %}</li>
            {% endif %}
            {% for item in page_obj %}
                <li class="py-3 first:pt-0 last:pb-0">
                    {% if is_fk %}
                        {% include "episodes/_episode.html" with episode=item.episode %}
                    {% else %}
                        {% include "episodes/_episode.html" with episode=item %}
                    {% endif %}
                </li>
            {% endfor %}
            {% if has_other_pages %}
                <li class="pt-3">{% include "_pagination_links.html" %}</li>
            {% endif %}
        </ul>
    {% endwith %}
{% else %}
    {% include "_empty.html" %}
{% endif %}

templates/episodes/detail.html
{% extends "base.html" %}
{% load cache heroicons partials %}
{% block title %}
    | {{ episode.podcast.cleaned_title }} | {{ episode.cleaned_title }}
{% endblock title %}
{% block content %}
    {% cache 600 episode-nav-header episode.pk %}
    {% with next_episode=episode.get_next_episode previous_episode=episode.get_previous_episode %}
        <header class="pb-3 mb-6 border-b space-y-6">
            <h1 class="text-lg font-bold md:text-xl xl:text-2xl">{{ episode.cleaned_title }}</h1>
            {% if next_episode or previous_episode %}
                <nav>
                    <ul class="flex justify-between"
                        role="navigation"
                        aria-label="Pagination">
                        <li>
                            {% if previous_episode %}
                                <a class="link"
                                   href="{{ previous_episode.get_absolute_url }}"
                                   aria-label="{{ previous_episode.cleaned_title }}"
                                   title="{{ previous_episode.cleaned_title }}">Previous</a>
                            {% else %}
                                <span class="text-gray-600 cursor-not-allowed dark:text-gray-300"
                                      title="First Episode"
                                      aria-label="First Episode">Previous</span>
                            {% endif %}
                        </li>
                        <li>
                            {% if next_episode %}
                                <a class="link"
                                   href="{{ next_episode.get_absolute_url }}"
                                   aria-label="{{ next_episode.cleaned_title }}"
                                   title="{{ next_episode.cleaned_title }}">Next</a>
                            {% else %}
                                <span class="text-gray-600 cursor-not-allowed dark:text-gray-300"
                                      title="Last Episode"
                                      aria-label="Last Episode">Next</span>
                            {% endif %}
                        </li>
                    </ul>
                </nav>
            {% endif %}
        </header>
    {% endwith %}
{% endcache %}
{% with podcast=episode.podcast %}
    <article class="space-y-6">
        <h2 class="text-base md:text-lg">
            <a href="{{ podcast.get_episodes_url }}"
               aria-label="See all episodes for {{ podcast.cleaned_title }}"
               title="See all episodes for {{ podcast.cleaned_title }}"
               class="link">{{ podcast.cleaned_title }}</a>
        </h2>
        {% with episode_type=episode.get_episode_type episode_num=episode.episode season=episode.season %}
            {% if episode_type or episode_num or season %}
                <div class="flex items-center font-semibold text-gray-800 space-x-3 dark:text-gray-300">
                    {% if episode_type %}{{ episode_type|capfirst }}{% endif %}
                    {% if episode_num %}Episode {{ episode_num }}{% endif %}
                    {% if season %}Season {{ season }}{% endif %}
                </div>
            {% endif %}
        {% endwith %}
        <div class="flex items-center space-x-3 sm:space-x-6">
            {% cover_image episode.get_cover_url 200 podcast.cleaned_title url=podcast.get_absolute_url css_class="h-32 w-32 md:h-40 md:w-40" %}
            <div class="flex flex-col place-content-between h-28 md:h-32">
                {% partialdef audio_player_button inline=True %}
                {% with target="audio-player-button" %}
                    <div id="{{ target }}"
                         hx-push-url="false"
                         hx-target="this"
                         hx-indicator="this"
                         hx-swap="outerHTML">
                        {% if is_playing %}
                            <button aria-label="Close Player"
                                    title="Close Player"
                                    class="inline-flex items-center btn btn-primary btn-outline btn-lg"
                                    hx-post="{% url 'episodes:close_player' %}"
                                    hx-trigger="click once">
                                {% heroicon_mini "stop-circle" class="mr-2" %}
                                Close
                            </button>
                        {% else %}
                            <button aria-label="Open Episode in Player"
                                    title="Open Episode in Player"
                                    class="inline-flex items-center btn btn-primary btn-lg"
                                    hx-post="{% url 'episodes:start_player' episode.pk %}"
                                    hx-trigger="click once">
                                {% heroicon_mini "play-circle" class="mr-2" %}
                                Play
                            </button>
                        {% endif %}
                        {% if request.htmx.target == target %}
                            {% with hx_oob=True %}
                                {% partial audio_log %}
                                {% include "episodes/_audio_player.html" %}
                            {% endwith %}
                        {% endif %}
                    </div>
                {% endwith %}
            {% endpartialdef audio_player_button %}
            {% partialdef bookmark_button inline=True %}
            <div hx-push-url="false"
                 hx-target="this"
                 hx-swap="outerHTML"
                 hx-indicator="this">
                {% if is_bookmarked %}
                    <button aria-label="Remove episode from your Bookmarks"
                            title="Remove episode from your Bookmarks"
                            class="inline-flex items-center btn btn-default btn-outline"
                            hx-delete="{% url 'episodes:remove_bookmark' episode.pk %}"
                            hx-trigger="click once">
                        {% heroicon_mini "bookmark-slash" class="mr-2" %}
                        Bookmark
                    </button>
                {% else %}
                    <button aria-label="Add episode to your Bookmarks"
                            title="Add episode to your Bookmarks"
                            class="inline-flex items-center btn btn-default"
                            hx-post="{% url 'episodes:add_bookmark' episode.pk %}"
                            hx-trigger="click once">
                        {% heroicon_mini "bookmark" class="mr-2" %}
                        Bookmark
                    </button>
                {% endif %}
            </div>
        {% endpartialdef bookmark_button %}
        <div class="flex flex-wrap items-center font-semibold text-gray-800 dark:text-gray-300 space-x-2 sm:space-x-3">
            <a download
               aria-label="Download audio file to your device"
               title="Download audio file to your device"
               href="{{ episode.media_url }}"
               class="link">Download</a>
            {% with website=episode.webside|default:podcast.website %}
                {% if website %}
                    <a href="{{ website }}"
                       target="_blank"
                       rel="noopener"
                       class="link"
                       title="Link to Website">Website</a>
                {% endif %}
            {% endwith %}
        </div>
    </div>
</div>
<div class="flex items-center font-semibold text-gray-600 dark:text-gray-300 space-x-3">
    {% include "_date.html" with value=episode.pub_date title="Release Date" %}
    {% with file_size=episode.get_file_size %}
        {% if file_size %}<div title="Size">{{ file_size }}</div>{% endif %}
    {% endwith %}
    {% with duration=episode.duration_in_seconds %}
        {% if duration %}<span title="Duration">{{ duration|format_duration }}</span>{% endif %}
    {% endwith %}
    {% if episode.is_explicit %}
        <div title="May contain adult themes and language. Listener discretion advised."
             class="flex items-center text-red-600 dark:text-red-500 space-x-2">
            {% heroicon_outline "exclamation-triangle" size=20 %} <span class="inline-block">Explicit</span>
        </div>
    {% endif %}
</div>
{% partialdef audio_log inline=True %}
<div id="audio-log"{% if hx_oob %} hx-swap-oob="true"{% endif %}>
    {% if audio_log %}
        <div class="flex flex-wrap items-center font-semibold text-gray-600 space-x-3 dark:text-gray-300">
            <div class="flex items-center space-x-1">
                <span>Listened</span>
                {% include "_date.html" with value=audio_log.listened title="Listened" %}
            </div>
            {% with current_time=audio_log.current_time %}
                {% if current_time and current_time > 60 %}<div title="Timestamp">{{ current_time|format_duration }}</div>{% endif %}
            {% endwith %}
            {% if not is_playing %}
                <button class="inline-flex items-center text-xs btn btn-danger lg:text-sm"
                        title="Remove episode from your History"
                        hx-target="#audio-log"
                        hx-delete="{% url "episodes:remove_audio_log" episode.pk %}"
                        hx-indicator="this"
                        hx-push-url="false"
                        hx-swap="outerHTML"
                        hx-confirm="Are you sure you want to remove this episode from your History?">
                    {% heroicon_mini "trash" class="mr-2" %}
                    Remove
                </button>
            {% endif %}
        </div>
    {% endif %}
</div>
{% endpartialdef audio_log %}
{% markdown episode.description %}
</article>
{% endwith %}
{% endblock content %}