radiofeed/episodes/urls.py
from django.urls import path

from radiofeed.episodes import views

app_name = "episodes"


urlpatterns = [
    path("new/", views.index, name="index"),
    path("search/episodes/", views.search_episodes, name="search_episodes"),
    path(
        "episodes/<int:episode_id>/<slug:slug>/",
        views.episode_detail,
        name="episode_detail",
    ),
    path(
        "player/start/<int:episode_id>/",
        views.start_player,
        name="start_player",
    ),
    path(
        "player/close/",
        views.close_player,
        name="close_player",
    ),
    path(
        "player/timeupdate/",
        views.player_time_update,
        name="player_time_update",
    ),
    path("history/", views.history, name="history"),
    path(
        "history/<int:episode_id>/remove/",
        views.remove_audio_log,
        name="remove_audio_log",
    ),
    path("bookmarks/", views.bookmarks, name="bookmarks"),
    path(
        "bookmarks/<int:episode_id>/add/",
        views.add_bookmark,
        name="add_bookmark",
    ),
    path(
        "bookmarks/<int:episode_id>/remove/",
        views.remove_bookmark,
        name="remove_bookmark",
    ),
]

radiofeed/podcasts/urls.py
from django.urls import path

from radiofeed.podcasts import views

app_name = "podcasts"

urlpatterns = [
    path("", views.landing_page, name="landing_page"),
    path("podcasts/", views.index, name="index"),
    path(
        "podcasts/<int:podcast_id>/<slug:slug>/",
        views.podcast_detail,
        name="podcast_detail",
    ),
    path(
        "podcasts/<int:podcast_id>/<slug:slug>/latest/",
        views.latest_episode,
        name="latest_episode",
    ),
    path(
        "podcasts/<int:podcast_id>/<slug:slug>/episodes/",
        views.episodes,
        name="podcast_episodes",
    ),
    path(
        "podcasts/<int:podcast_id>/<slug:slug>/similar/",
        views.similar,
        name="podcast_similar",
    ),
    path("search/podcasts/", views.search_podcasts, name="search_podcasts"),
    path("search/itunes/", views.search_itunes, name="search_itunes"),
    path(
        "subscribe/<int:podcast_id>/",
        views.subscribe,
        name="subscribe",
    ),
    path(
        "unsubscribe/<int:podcast_id>/",
        views.unsubscribe,
        name="unsubscribe",
    ),
    path(
        "categories/",
        views.category_list,
        name="category_list",
    ),
    path(
        "categories/<int:category_id>/<slug:slug>/",
        views.category_detail,
        name="category_detail",
    ),
    path(
        "private-feeds/",
        views.private_feeds,
        name="private_feeds",
    ),
    path(
        "private-feeds/new/",
        views.add_private_feed,
        name="add_private_feed",
    ),
    path(
        "private-feeds/remove/<int:podcast_id>/",
        views.remove_private_feed,
        name="remove_private_feed",
    ),
]

radiofeed/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from radiofeed import views

admin.site.site_header = settings.ADMIN_SITE_HEADER


urlpatterns = [
    path("", include("radiofeed.episodes.urls")),
    path("", include("radiofeed.podcasts.urls")),
    path("", include("radiofeed.users.urls")),
    path("account/", include("allauth.urls")),
    path("about/", views.about_page, name="about"),
    path("health-check/", views.health_check, name="health_check"),
    path("accept-cookies/", views.accept_cookies, name="accept_cookies"),
    path("covers/<int:size>/cover.webp", views.cover_image, name="cover_image"),
    path("robots.txt", views.robots, name="robots"),
    path("service-worker.js", views.service_worker, name="service_worker"),
    path("manifest.json", views.manifest, name="manifest"),
    path("favicon.ico", views.favicon, name="favicon"),
    path(".well-known/security.txt", views.security, name="security"),
    path(settings.ADMIN_URL, admin.site.urls),
]

if "django_browser_reload" in settings.INSTALLED_APPS:  # pragma: no cover
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

if "debug_toolbar" in settings.INSTALLED_APPS:  # pragma: no cover
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

radiofeed/users/urls.py
from django.urls import path

from radiofeed.users import views

app_name = "users"

urlpatterns = [
    path("account/preferences/", views.user_preferences, name="preferences"),
    path("account/stats/", views.user_stats, name="stats"),
    path(
        "account/feeds/",
        views.manage_podcast_feeds,
        name="manage_podcast_feeds",
    ),
    path(
        "account/feeds/export/",
        views.export_podcast_feeds,
        name="export_podcast_feeds",
    ),
    path(
        "account/feeds/import/",
        views.import_podcast_feeds,
        name="import_podcast_feeds",
    ),
    path("account/delete/", views.delete_account, name="delete_account"),
]

templates/403_csrf.html
{% extends "403.html" %}
{% block content %}
    <h1 class="mb-6 font-bold text-lg md:text-xl xl:text-2xl">400: Bad Request</h1>
    <p class="mb-6">Sorry, there's been a problem posting your form. Please reload this page and try again.</p>
    <p>
        <a class="btn btn-primary" href="{{ request.get_full_path }}">Reload Page</a>
    </p>
{% endblock content %}

templates/405.html
{% extends "error_base.html" %}
{% block title %}
    Error: 405 Method Not Allowed
{% endblock title %}
{% block content %}
    <h1 class="mb-6 font-bold text-lg md:text-xl xl:text-2xl">405: Method Not Allowed</h1>
    <p>
        Sorry, you cannot perform this action. You may have disabled JavaScript on your browser or are using an older browser that does not support this action.
    </p>
{% endblock content %}

templates/_cookie_notice.html
{# vim: set filetype=htmldjango #}
{% if not accept_cookies %}
    <div class="fixed bottom-0 z-50 flex justify-center w-full py-3 text-white bg-black opacity-90"
         id="accept-cookies">
        <div class="px-2">
            <div class="items-center md:flex">
                <p class="mb-3 font-bold text-center md:mb-0 md:mr-4 md:text-start">
                    This site uses cookies to ensure you get the best experience.
                </p>
                <div class="text-center md:text-start">
                    <button class="px-4 py-1 text-base border border-white btn btn-primary md:text-lg"
                            aria-label="OK, I accept cookies"
                            title="OK, I accept cookies"
                            hx-post="{% url 'accept_cookies' %}"
                            hx-target="#accept-cookies"
                            hx-push-url="false"
                            hx-swap="delete"
                            hx-indicator="this">OK</button>
                </div>
            </div>
        </div>
    </div>
{% endif %}

templates/_cover_image.html
{% spaceless %}
    <img class="object-cover border bg-transparent{% if url %} hover:grayscale cursor-pointer{% endif %} {{ css_class }}"
        title="{{ title }}"
        alt="{{ title }}"
        aria-hidden="true"
        loading="lazy"
        decoding="async"
        width="{{ size }}"
        height="{{ size }}"
        src="{{ cover_url|default:placeholder }}"
        {% if url %}
            role="link"
            hx-get="{{ url }}"
            hx-push-url="true"
            hx-trigger="click consume"
        {% endif %}
        {% if cover_url %}
            {# djlint:off #}
            x-data="{
            isLoaded: false,
            src: '{{ cover_url|escapejs }}',
            placeholder: '{{ placeholder|escapejs }}'}"
            {# djlint:on #}
            @load.once="isLoaded=true;"
            @error.once="src=placeholder;isLoaded=true;"
            :src="isLoaded ? src : placeholder"
        {% endif %}>
    {% endspaceless %}

templates/_empty.html
<p class="text-center sm:text-left py-2">
    {% if request.search %}
        No results found for <span class="font-bold">{{ request.search.value }}</span>.
    {% else %}
        Nothing to see here.
    {% endif %}
</p>

templates/_hx_indicator.html
<div id="hx-indicator"
    x-data="{width: 0}"
    {# djlint:off #}
    x-init="
    setInterval(() => {
        if ($el.classList.contains('htmx-request')) {
            width = width + (Math.random() / 100) + 1;
            width = width > 30 ? width = -30 : width;
        } else {
            width = 0;
        }
        $el.style.width = width > 0 ? `${10 + (width * 90)}%` : '0px';
    }, 36);"{# djlint:on #}></div>

templates/_navbar.html
{% load static heroicons %}
<header class="sticky top-0 z-20 w-full text-white bg-violet-900"
        :class="scrolling ? 'drop-shadow-xl': ''"
        x-data="{showMenu: false, scrolling: false}"
        @scroll.window="scrolling = window.pageYOffset > 0"
        @htmx:before-request.window="showMenu=false">
    <nav class="flex items-center justify-between p-2">
        {% with site_name=request.site.name %}
            <div class="flex items-center flex-shrink-0">
                <a class="inline-flex items-center text-lg font-bold md:text-xl xl:text-2xl"
                   href="{% if user.is_authenticated %}{% url 'podcasts:index' %}{% else %}{% url 'podcasts:landing_page' %}{% endif %}"
                   title="{{ site_name }}: Home Page">
                    <img src="{% static 'img/wave-white.png' %}"
                         height="100"
                         width="100"
                         alt="{{ site_name }}"
                         class="w-6 h-6 mr-3 lg:h-8 lg:w-8"
                         title="{{ site_name }}"
                         aria-hidden="true">
                    {{ site_name }}
                </a>
            </div>
        {% endwith %}
        <ul class="flex items-center space-x-3">
            {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'users:preferences' %}"
                       aria-label="Settings for {{ user.username }}"
                       title="Settings for {{ user.username }}"
                       class="flex items-center font-bold">{{ user.username|slice:12 }}</a>
                </li>
                <li class="flex items-center xl:hidden">
                    <button class="focus:outline-none transform transition"
                            aria-label="Show Menu"
                            title="Show Menu"
                            x-cloak
                            x-show.transition="!showMenu"
                            @click="showMenu=true">{% heroicon_outline "bars-3" size=30 title="Toggle Menu" %}</button>
                    <button class="focus:outline-none transform transition"
                            aria-label="Hide Menu"
                            title="Hide Menu"
                            x-cloak
                            x-show.transition="showMenu"
                            @click="showMenu=false"
                            @keyup.escape.window="showMenu=false">
                        {% heroicon_outline "x-mark" size=30 title="Toggle Menu" %}
                    </button>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'about' %}"
                       aria-label="About this Site"
                       title="About this Site"
                       class="flex items-center font-bold space-x-2 hover:text-blue-300">
                        {% heroicon_outline "information-circle" size=30 title="Toggle Menu" %}
                        <span class="hidden md:inline-block">About</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
    {% if user.is_authenticated %}
        <div class="absolute left-0 z-50 w-full py-6 bg-white shadow-xl xl:hidden dark:bg-black"
             x-cloak
             x-show.transition="showMenu"
             x-transition:enter="transition ease-out duration-75"
             x-transition:enter-start="transform opacity-0 scale-95"
             x-transition:enter-end="transform opacity-100 scale-100"
             x-transition:leave="transition ease-in duration-75"
             x-transition:leave-start="transform opacity-100 scale-100"
             x-transition:leave-end="transform opacity-0 scale-95">{% include "_sidebar.html" %}</div>
    {% endif %}
    {% include "_signup_cta.html" %}
</header>

templates/_pagination_links.html
{# vim: set filetype=htmldjango #}
<nav role="navigation"
     aria-label="Pagination"
     hx-swap="outerHTML show:window:top"
     hx-target="#{{ pagination_target }}">
    <ul class="flex items-center justify-between">
        <li>
            {% if page_obj.has_previous %}
                <a class="link"
                   href="{% pagination_url page_obj.previous_page_number %}"
                   aria-label="Previous Page"
                   title="Previous Page">Previous</a>
            {% else %}
                <span class="text-gray-600 cursor-not-allowed dark:text-gray-300"
                      title="First Page"
                      aria-label="First Page">Previous</span>
            {% endif %}
        </li>
        <li>
            {% if page_obj.has_next %}
                <a class="link"
                   aria-label="Next Page"
                   href="{% pagination_url page_obj.next_page_number %}"
                   title="Next Page">Next</a>
            {% else %}
                <span class="text-gray-600 cursor-not-allowed dark:text-gray-300"
                      title="Last Page"
                      aria-label="Last Page">Next</span>
            {% endif %}
        </li>
    </ul>
</nav>

templates/_search_form.html
{% load heroicons %}
<form action="{{ search_url|default:request.path }}"
      method="get"
      class="relative bg-transparent"
      x-data="{search: '{{ request.search.value|default:''|escapejs }}'}"
      hx-push-url="true">
    <input type="search"
           x-model="search"
           name="{{ request.search.param }}"
           autocomplete="off"
           aria-label="{{ placeholder|default:"Search" }}"
           {% if placeholder %}placeholder="{{ placeholder }}"{% endif %}
           class="w-64 px-2 py-1 text-gray-900 rounded focus:outline-none focus:ring placeholder-opacity-100 dark:bg-gray-900 dark:text-white text-sm md:text-base"
           :class="{ 'md:w-72 xl:w-84': !search, 'md:w-72 xl:w-96': search }">
    <div class="absolute inset-y-0 right-0 flex items-center pr-2">
        <a href="{{ clear_search_url|default:request.path }}"
           title="Clear Search"
           aria-label="Clear Search"
           class="mr-2 text-gray-900 focus:outline-none focus:shadow-outline dark:text-gray-100"
           x-show="search"
           x-cloak>{% heroicon_mini "x-mark" title="Clear Search" %}</a>
        <button type="submit"
                title="Search"
                aria-label="Search"
                class="text-gray-900 focus:outline-none focus:shadow-outline dark:text-gray-100">
            {% heroicon_mini "magnifying-glass" title="Search" %}
        </button>
    </div>
</form>

templates/_sidebar.html
{% load heroicons %}
{% with SIDEBAR_CSS="inline-flex items-center w-full sm:w-auto link" ICON_CSS="mr-3 lg:mr-6" %}
    <nav class="pl-3 text-base xl:pl-0 xl:pt-12 md:text-lg lg:text-xl">
        <ul class="space-y-3 sm:space-y-0 xl:space-y-3 sm:grid sm:gap-3 sm:grid-flow-cols sm:grid-cols-2 xl:flex xl:flex-col xl:justify-content-between">
            <li>
                <a href="{% url 'podcasts:index' %}"
                   accesskey="p"
                   class="{{ SIDEBAR_CSS }}">
                    {% heroicon_outline "rss" class=ICON_CSS %}
                    Podcasts
                </a>
            </li>
            <li>
                <a href="{% url 'episodes:index' %}"
                   accesskey="n"
                   class="{{ SIDEBAR_CSS }}">
                    {% heroicon_outline "sparkles" class=ICON_CSS %}
                    New Releases
                </a>
            </li>
            <li>
                <a href="{% url 'podcasts:category_list' %}"
                   accesskey="c"
                   class="{{ SIDEBAR_CSS }}">
                    {% heroicon_outline "tag" class=ICON_CSS %}
                    Categories
                </a>
            </li>
            <li>
                <a href="{% url 'episodes:bookmarks' %}"
                   accesskey="b"
                   class="{{ SIDEBAR_CSS }}">
                    {% heroicon_outline "bookmark" class=ICON_CSS %}
                    Bookmarks
                </a>
            </li>
            <li>
                <a href="{% url 'episodes:history' %}"
                   accesskey="h"
                   class="{{ SIDEBAR_CSS }}">
                    {% heroicon_outline "clock" class=ICON_CSS %}
                    History
                </a>
            </li>
            <li>
                <a href="{% url 'podcasts:private_feeds' %}"
                   accesskey="f"
                   class="{{ SIDEBAR_CSS }}">
                    {% heroicon_outline "lock-closed" class=ICON_CSS %}
                    Private Feeds
                </a>
            </li>
            <li>
                <a href="{% url 'users:preferences' %}"
                   accesskey="s"
                   class="{{ SIDEBAR_CSS }}">
                    {% heroicon_outline "cog-6-tooth" class=ICON_CSS %}
                    Settings
                </a>
            </li>
            <li>
                <a href="{% url 'about' %}" accesskey="a" class="{{ SIDEBAR_CSS }}">
                    {% heroicon_outline "information-circle" class=ICON_CSS %}
                    About
                </a>
            </li>
            <li>
                <form class="{{ SIDEBAR_CSS }}"
                      hx-disable="true"
                      action="{% url 'account_logout' %}"
                      method="post">
                    {% csrf_token %}
                    <button accesskey="l" class="{{ SIDEBAR_CSS }}">
                        {% heroicon_outline "arrow-left-on-rectangle" class=ICON_CSS %}
                        Logout
                    </button>
                </form>
            </li>
        </ul>
    </nav>
{% endwith %}

templates/base.html
{% extends request.htmx|yesno:"hx_base.html,default_base.html" %}

templates/error_base.html
{% spaceless %}
    {% load static %}
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <title>
                {# djlint:off #}
                {% block title %}{% endblock title %}
                {# djlint:on #}
            </title>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport"
                  content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <meta name="copyright" content="Dan Jacob {% now "Y" %}">
            <meta name="robots" content="nofollow" />
            <link rel="icon" type="image/png" href="{% static 'img/wave-ico.png' %}">
            <link rel="apple-touch-icon image_src"
                  href="{% static 'img/apple-touch-icon.png' %}">
            <link href="{% static "css/bundle.css" %}{% if debug %}?{% now "U" %}{% endif %}" rel="stylesheet" type="text/css" media="screen">
        </head>
        <body class="mx-auto font-sans text-sm antialiased container-xl dark:bg-zinc-900 dark:text-white md:text-base scroll-smooth">
            {% url 'podcasts:index' as home_url %}
            <header class="sticky top-0 z-20 w-full text-white bg-violet-900">
                {% with site_name="Radiofeed" %}
                    <nav class="flex items-center justify-between p-2">
                        <div class="flex items-center flex-shrink-0 space-x-3">
                            <a class="inline-flex items-center text-lg font-bold md:text-xl xl:text-2xl hover:text-blue-300"
                               href="{{ home_url }}"
                               title="{{ site_name }}: Home Page">
                                <img src="{% static 'img/wave-white.png' %}"
                                     alt="{{ site_name }}"
                                     height="100"
                                     width="100"
                                     class="w-6 h-6 mr-2 lg:h-8 lg:w-8"
                                     title="{{ site_name }}"
                                     aria-hidden="true">
                                {{ site_name }}
                            </a>
                        </div>
                    </nav>
                {% endwith %}
            </header>
            <main class="flex justify-center w-full min-h-screen mt-12">
                <div class="justify-center w-full text-center md:w-4/5 xl:w-1/3">
                    {# djlint:off #}
                    {% block content %}{% endblock content %}
                    {# djlint:on #}
                </div>
            </main>
        </body>
    </html>
{% endspaceless %}

templates/hx_base.html
{% spaceless %}
    <title>
        {{ request.site.name }}
        {# djlint:off #}
        {% block title %}{% endblock title %}
        {# djlint:on #}
    </title>
    {# djlint:off #}
    {% block content %}{% endblock content %}
    {# djlint:on #}
{% endspaceless %}

templates/search_base.html
{% extends "base.html" %}
{% block content %}
    <header class="pb-3 mb-3 border-b space-y-6">
        <h1 class="flex items-center justify-center text-lg font-bold sm:justify-start lg:text-xl xl:text-2xl">
            Search {{ request.site.name }}
        </h1>
        <nav class="justify-between sm:flex space-y-3 sm:space-y-0">
            <ul class="flex items-center justify-center overflow-x-auto space-x-6 sm:justify-start md:overflow-none whitespace-nowrap md:whitespace-none">
                {% with search_qs="?"|add:request.search.qs %}
                    {% active_link 'podcasts:search_podcasts' as link %}
                    <li>
                        <a class="{{ link.css }}"
                           title="Search Podcasts"
                           href="{{ link.url|add:search_qs }}">Podcasts</a>
                    </li>
                    {% active_link 'episodes:search_episodes' as link %}
                    <li>
                        <a class="{{ link.css }}"
                           title="Search Episodes"
                           href="{{ link.url|add:search_qs }}">Episodes</a>
                    </li>
                    {% active_link 'podcasts:search_itunes' as link %}
                    <li>
                        <a class="{{ link.css }}"
                           title="Search iTunes"
                           href="{{ link.url|add:search_qs }}">iTunes</a>
                    </li>
                {% endwith %}
            </ul>
            <ul class="flex items-center justify-center sm:justify-end">
                <li>{% include "_search_form.html" with placeholder="Search..." %}</li>
            </ul>
        </nav>
    </header>
    {# djlint:off #}
    {% block search_content %}{% endblock search_content %}
    {# djlint:on #}
{% endblock content %}