radiofeed/episodes/urls.py
from django.urls import path

from radiofeed.episodes import views

app_name = "episodes"


urlpatterns = [
    path("new/", views.index, name="index"),
    path("search/episodes/", views.search_episodes, name="search_episodes"),
    path(
        "episodes/<int:episode_id>/<slug:slug>/",
        views.episode_detail,
        name="episode_detail",
    ),
    path(
        "player/start/<int:episode_id>/",
        views.start_player,
        name="start_player",
    ),
    path(
        "player/close/",
        views.close_player,
        name="close_player",
    ),
    path(
        "player/timeupdate/",
        views.player_time_update,
        name="player_time_update",
    ),
    path("history/", views.history, name="history"),
    path(
        "history/<int:episode_id>/remove/",
        views.remove_audio_log,
        name="remove_audio_log",
    ),
    path("bookmarks/", views.bookmarks, name="bookmarks"),
    path(
        "bookmarks/<int:episode_id>/add/",
        views.add_bookmark,
        name="add_bookmark",
    ),
    path(
        "bookmarks/<int:episode_id>/remove/",
        views.remove_bookmark,
        name="remove_bookmark",
    ),
]

radiofeed/podcasts/urls.py
from django.urls import path

from radiofeed.podcasts import views

app_name = "podcasts"

urlpatterns = [
    path("", views.landing_page, name="landing_page"),
    path("podcasts/", views.index, name="index"),
    path(
        "podcasts/<int:podcast_id>/<slug:slug>/",
        views.podcast_detail,
        name="podcast_detail",
    ),
    path(
        "podcasts/<int:podcast_id>/<slug:slug>/latest/",
        views.latest_episode,
        name="latest_episode",
    ),
    path(
        "podcasts/<int:podcast_id>/<slug:slug>/episodes/",
        views.episodes,
        name="podcast_episodes",
    ),
    path(
        "podcasts/<int:podcast_id>/<slug:slug>/similar/",
        views.similar,
        name="podcast_similar",
    ),
    path("search/podcasts/", views.search_podcasts, name="search_podcasts"),
    path("search/itunes/", views.search_itunes, name="search_itunes"),
    path(
        "subscribe/<int:podcast_id>/",
        views.subscribe,
        name="subscribe",
    ),
    path(
        "unsubscribe/<int:podcast_id>/",
        views.unsubscribe,
        name="unsubscribe",
    ),
    path(
        "categories/",
        views.category_list,
        name="category_list",
    ),
    path(
        "categories/<int:category_id>/<slug:slug>/",
        views.category_detail,
        name="category_detail",
    ),
    path(
        "private-feeds/",
        views.private_feeds,
        name="private_feeds",
    ),
    path(
        "private-feeds/new/",
        views.add_private_feed,
        name="add_private_feed",
    ),
    path(
        "private-feeds/remove/<int:podcast_id>/",
        views.remove_private_feed,
        name="remove_private_feed",
    ),
]

radiofeed/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from radiofeed import views

admin.site.site_header = settings.ADMIN_SITE_HEADER


urlpatterns = [
    path("", include("radiofeed.episodes.urls")),
    path("", include("radiofeed.podcasts.urls")),
    path("", include("radiofeed.users.urls")),
    path("account/", include("allauth.urls")),
    path("about/", views.about_page, name="about"),
    path("health-check/", views.health_check, name="health_check"),
    path("accept-cookies/", views.accept_cookies, name="accept_cookies"),
    path("covers/<int:size>/cover.webp", views.cover_image, name="cover_image"),
    path("robots.txt", views.robots, name="robots"),
    path("service-worker.js", views.service_worker, name="service_worker"),
    path("manifest.json", views.manifest, name="manifest"),
    path("favicon.ico", views.favicon, name="favicon"),
    path(".well-known/security.txt", views.security, name="security"),
    path(settings.ADMIN_URL, admin.site.urls),
]

if "django_browser_reload" in settings.INSTALLED_APPS:  # pragma: no cover
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]

if "debug_toolbar" in settings.INSTALLED_APPS:  # pragma: no cover
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

radiofeed/podcasts/forms.py
from django import forms

from radiofeed.podcasts.models import Podcast, Subscription
from radiofeed.users.models import User


class PrivateFeedForm(forms.Form):
    """Form to add a private feed."""

    rss = forms.URLField(max_length=300, label="Feed RSS")

    def __init__(self, user: User, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_rss(self) -> str:
        """Validates RSS."""
        value = self.cleaned_data["rss"]

        if Subscription.objects.filter(
            subscriber=self.user, podcast__rss=value
        ).exists():
            raise forms.ValidationError("You are already subscribed to this podcast")

        if Podcast.objects.filter(rss=value, private=False).exists():
            raise forms.ValidationError("This is not a private feed")

        return value

    def save(self) -> tuple[Podcast, bool]:
        """Adds new podcast.

        Returns podcast instance and boolean to indicate podcast is new.
        """
        podcast, is_new = Podcast.objects.get_or_create(
            rss=self.cleaned_data["rss"],
            defaults={"private": True},
        )
        is_new = is_new or podcast.pub_date is None
        Subscription.objects.create(subscriber=self.user, podcast=podcast)
        return podcast, is_new

radiofeed/episodes/views.py
from datetime import timedelta

from django.contrib import messages
from django.db import IntegrityError
from django.db.models import Exists, OuterRef
from django.http import Http404, HttpRequest, HttpResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.http import require_POST, require_safe

from radiofeed.decorators import require_auth, require_DELETE
from radiofeed.episodes.models import AudioLog, Episode
from radiofeed.htmx import render_htmx
from radiofeed.http import HttpResponseConflict, HttpResponseNoContent
from radiofeed.pagination import render_pagination


@require_safe
@require_auth
def index(request: HttpRequest) -> HttpResponse:
    """List latest episodes from subscriptions if any, else latest episodes from
    promoted podcasts."""
    episodes = (
        Episode.objects.filter(pub_date__gt=timezone.now() - timedelta(days=14))
        .select_related("podcast")
        .order_by("-pub_date", "-id")
    )

    subscribed = episodes.annotate(
        is_subscribed=Exists(
            request.user.subscriptions.filter(podcast=OuterRef("podcast"))
        )
    ).filter(is_subscribed=True)

    has_subscriptions = subscribed.exists()
    promoted = "promoted" in request.GET or not has_subscriptions

    episodes = episodes.filter(podcast__promoted=True) if promoted else subscribed

    return render_pagination(
        request,
        episodes,
        "episodes/index.html",
        {
            "promoted": promoted,
            "has_subscriptions": has_subscriptions,
            "search_url": reverse("episodes:search_episodes"),
        },
    )


@require_safe
@require_auth
def search_episodes(request: HttpRequest) -> HttpResponse:
    """Search episodes. If search empty redirects to index page."""
    if request.search:
        episodes = (
            Episode.objects.search(request.search.value)
            .filter(podcast__private__isnull=False)
            .select_related("podcast")
            .order_by("-rank", "-pub_date")
        )
        return render_pagination(request, episodes, "episodes/search.html")
    return redirect("episodes:index")


@require_safe
@require_auth
def episode_detail(
    request: HttpRequest, episode_id: int, slug: str | None = None
) -> HttpResponse:
    """Renders episode detail."""
    episode = get_object_or_404(
        Episode.objects.select_related("podcast"),
        pk=episode_id,
    )
    return _render_episode_detail(
        request,
        episode,
        {
            "audio_log": request.user.audio_logs.filter(episode=episode).first(),
            "is_bookmarked": request.user.bookmarks.filter(episode=episode).exists(),
            "is_playing": request.player.has(episode.pk),
        },
    )


@require_POST
@require_auth
def start_player(request: HttpRequest, episode_id: int) -> HttpResponse:
    """Starts player. Creates new audio log if required."""
    episode = get_object_or_404(
        Episode.objects.select_related("podcast"),
        pk=episode_id,
    )

    audio_log, _ = request.user.audio_logs.update_or_create(
        episode=episode,
        defaults={
            "listened": timezone.now(),
        },
    )

    request.player.set(episode.pk)

    return _render_audio_player_button(request, audio_log, is_playing=True)


@require_POST
@require_auth
def close_player(request: HttpRequest) -> HttpResponse:
    """Closes audio player."""
    if episode_id := request.player.pop():
        audio_log = get_object_or_404(
            request.user.audio_logs.select_related("episode"),
            episode__pk=episode_id,
        )
        return _render_audio_player_button(request, audio_log, is_playing=False)

    return HttpResponseNoContent()


@require_POST
@require_auth
def player_time_update(request: HttpRequest) -> HttpResponse:
    """Update current play time of episode.

    Time should be passed in POST as `current_time` integer value.

    Returns:
        HTTP BAD REQUEST if missing/invalid `current_time`, otherwise HTTP NO CONTENT.
    """
    if episode_id := request.player.get():
        try:
            request.user.audio_logs.update_or_create(
                episode=get_object_or_404(Episode, pk=episode_id),
                defaults={
                    "current_time": int(request.POST["current_time"]),
                    "listened": timezone.now(),
                },
            )
        except (KeyError, ValueError):
            return HttpResponseBadRequest()

    return HttpResponseNoContent()


@require_safe
@require_auth
def history(request: HttpRequest) -> HttpResponse:
    """Renders user's listening history. User can also search history."""
    audio_logs = request.user.audio_logs.select_related("episode", "episode__podcast")

    if request.search:
        audio_logs = audio_logs.search(request.search.value).order_by(
            "-rank", "-listened"
        )
    else:
        audio_logs = audio_logs.order_by(
            "-listened" if request.ordering.is_desc else "listened"
        )

    return render_pagination(request, audio_logs, "episodes/history.html")


@require_DELETE
@require_auth
def remove_audio_log(request: HttpRequest, episode_id: int) -> HttpResponse:
    """Removes audio log from user history and returns HTMX snippet."""
    # cannot remove episode if in player
    if request.player.has(episode_id):
        raise Http404

    audio_log = get_object_or_404(
        request.user.audio_logs.select_related("episode"),
        episode__pk=episode_id,
    )

    audio_log.delete()

    messages.info(request, "Removed from History")
    return _render_episode_detail(request, audio_log.episode, partial="audio_log")


@require_safe
@require_auth
def bookmarks(request: HttpRequest) -> HttpResponse:
    """Renders user's bookmarks. User can also search their bookmarks."""
    bookmarks = request.user.bookmarks.select_related("episode", "episode__podcast")

    if request.search:
        bookmarks = bookmarks.search(request.search.value).order_by("-rank", "-created")
    else:
        bookmarks = bookmarks.order_by(
            "-created" if request.ordering.is_desc else "created"
        )

    return render_pagination(request, bookmarks, "episodes/bookmarks.html")


@require_POST
@require_auth
def add_bookmark(request: HttpRequest, episode_id: int) -> HttpResponse:
    """Add episode to bookmarks."""
    episode = get_object_or_404(Episode, pk=episode_id)

    try:
        request.user.bookmarks.create(episode=episode)
    except IntegrityError:
        return HttpResponseConflict()

    messages.success(request, "Added to Bookmarks")

    return _render_bookmark_button(request, episode, is_bookmarked=True)


@require_DELETE
@require_auth
def remove_bookmark(request: HttpRequest, episode_id: int) -> HttpResponse:
    """Remove episode from bookmarks."""
    episode = get_object_or_404(Episode, pk=episode_id)
    request.user.bookmarks.filter(episode=episode).delete()

    messages.info(request, "Removed from Bookmarks")

    return _render_bookmark_button(request, episode, is_bookmarked=False)


def _render_episode_detail(
    request: HttpRequest,
    episode: Episode,
    extra_context: dict | None = None,
    **kwargs,
) -> HttpResponse:
    return render_htmx(
        request,
        "episodes/detail.html",
        {
            "episode": episode,
            **(extra_context or {}),
        },
        **kwargs,
    )


def _render_bookmark_button(
    request: HttpRequest, episode: Episode, *, is_bookmarked: bool
) -> HttpResponse:
    return _render_episode_detail(
        request,
        episode,
        {"is_bookmarked": is_bookmarked},
        partial="bookmark_button",
    )


def _render_audio_player_button(
    request: HttpRequest, audio_log: AudioLog, *, is_playing: bool
) -> HttpResponse:
    return _render_episode_detail(
        request,
        audio_log.episode,
        {
            "audio_log": audio_log,
            "is_playing": is_playing,
            "start_player": is_playing,
        },
        partial="audio_player_button",
    )

templates/podcasts/_podcasts.html
{# vim: set filetype=htmldjango #}
{% if page_obj.paginator.count %}
    {% with has_other_pages=page_obj.has_other_pages %}
        <ul class="divide-y divide-solid" id="{{ pagination_target }}">
            {% if has_other_pages %}
                <li class="pb-3">{% include "_pagination_links.html" %}</li>
            {% endif %}
            {% for podcast in page_obj %}
                <li class="py-3 first:pt-0 last:pb-0">{% include "podcasts/_podcast.html" %}</li>
            {% endfor %}
            {% if has_other_pages %}
                <li class="pt-3">{% include "_pagination_links.html" %}</li>
            {% endif %}
        </ul>
    {% endwith %}
{% else %}
    {% include "_empty.html" %}
{% endif %}

templates/podcasts/category_detail.html
{% extends "base.html" %}
{% load cache partials %}
{% block title %}
    | Categories | {{ category.name }} Podcasts
{% endblock title %}
{% block content %}
    {% with search_placeholder="Search: "|add:category.name %}
        {% if request.search %}
            <header class="pb-3 mb-3 border-b space-y-3">
                <h1 class="flex items-center justify-center text-lg font-bold sm:justify-start md:text-xl xl:text-2xl">
                    {{ category.name }} Podcasts
                </h1>
                <nav>
                    <ul class="items-center justify-center space-y-3 sm:space-y-0 sm:flex sm:justify-between">
                        <li class="flex items-center justify-center sm:mb-0 sm:justify-start">
                            <a href="{% url 'podcasts:search_podcasts' %}?{{ request.search.qs }}"
                               aria-label="Search Podcasts"
                               title="Search Podcasts"
                               class="link">Search All Categories</a>
                        </li>
                        <li class="flex items-center justify-center sm:justify-end">
                            {% include "_search_form.html" with placeholder=search_placeholder %}
                        </li>
                    </ul>
                </nav>
            </header>
        {% else %}
            <header class="items-center justify-between pb-3 mb-3 border-b sm:flex space-y-3 sm:space-y-0">
                <h1 class="flex items-center justify-center text-lg font-bold sm:justify-start md:text-xl xl:text-2xl">
                    {{ category.name }} Podcasts
                </h1>
                <nav class="flex items-center justify-center sm:justify-end">
                    <ul>
                        <li>{% include "_search_form.html" with placeholder=search_placeholder %}</li>
                    </ul>
                </nav>
            </header>
        {% endif %}
    {% endwith %}
    {% partialdef pagination inline=True %}
    {% cache 600 category-detail request.get_full_path %}
    {% include "podcasts/_podcasts.html" %}
{% endcache %}
{% endpartialdef pagination %}
{% endblock content %}

templates/podcasts/detail.html
{% extends "podcasts/detail_base.html" %}
{% load cache heroicons partials %}
{% block podcast_content %}
    <article class="space-y-6">
        {% if podcast.owner %}
            <h2 class="text-base md:text-lg">
                {% if podcast.website %}
                    <a href="{{ podcast.website }}"
                       rel="noopener nofollow"
                       target="_blank"
                       aria-label="Podcast Owner"
                       title="Podcast Owner"
                       class="link">{{ podcast.owner }}</a>
                {% else %}
                    {{ podcast.owner }}
                {% endif %}
            </h2>
        {% endif %}
        <div class="flex items-center space-x-3 sm:space-x-6">
            {% cover_image podcast.cover_url 200 podcast.cleaned_title css_class="h-32 w-32 lg:h-40 lg:w-40" %}
            <div class="flex flex-col place-content-between h-28 lg:h-32">
                {% if podcast.private %}
                    <div>
                        {% if is_subscribed %}
                            <button class="inline-flex items-center btn btn-danger btn-lg"
                                    aria-label="Remove podcast from your private feeds"
                                    title="Remove podcast from your private feeds"
                                    hx-push-url="true"
                                    hx-confirm="Are you sure you want to remove this podcast? You can't undo this action!"
                                    hx-delete="{% url 'podcasts:remove_private_feed' podcast.pk %}">
                                {% heroicon_mini "trash" class="mr-2" %}
                                Remove
                            </button>
                        {% else %}
                            <button class="inline-flex items-center btn btn-primary btn-lg opacity:"
                                    aria-label="This is a private feed, you cannot subscribe to it."
                                    title="This is a private feed, you cannot subscribe to it."
                                    disabled>
                                {% heroicon_mini "eye-slash" class="mr-2" %}
                                Subscribe
                            </button>
                        {% endif %}
                    </div>
                {% else %}
                    {% partialdef subscribe_button inline=True %}
                    <div hx-target="this"
                         hx-push-url="false"
                         hx-indicator="this"
                         hx-swap="outerHTML">
                        {% if is_subscribed %}
                            <button class="inline-flex items-center btn btn-primary btn-outline btn-lg"
                                    aria-label="Unsubscribe from this Podcast"
                                    title="Unsubscribe from this Podcast"
                                    hx-delete="{% url 'podcasts:unsubscribe' podcast.pk %}"
                                    hx-trigger="click once">
                                {% heroicon_mini "eye-slash" class="mr-2" %}
                                Unsubscribe
                            </button>
                        {% else %}
                            <button class="inline-flex items-center btn btn-primary btn-lg"
                                    aria-label="Subscribe to this Podcast"
                                    title="Subscribe to this Podcast"
                                    hx-post="{% url 'podcasts:subscribe' podcast.pk %}"
                                    hx-trigger="click once">
                                {% heroicon_mini "eye" class="mr-2" %}
                                Subscribe
                            </button>
                        {% endif %}
                    </div>
                {% endpartialdef subscribe_button %}
            {% endif %}
            <nav class="flex items-center space-x-3">
                {% if podcast.website %}
                    <div>
                        <a href="{{ podcast.website }}"
                           class="link"
                           rel="noopener nofollow"
                           target="_blank">Website</a>
                    </div>
                {% endif %}
                {% if is_subscribed or not podcast.private %}
                    <div>
                        <a href="{{ podcast.rss }}" class="link" download>RSS</a>
                    </div>
                {% endif %}
                {% if user.is_staff %}
                    <div>
                        <a href="{% url 'admin:podcasts_podcast_change' podcast.pk %}"
                           hx-disable="true"
                           class="link">Admin</a>
                    </div>
                {% endif %}
            </nav>
            <div class="flex flex-wrap">
                <a href="{{ podcast.get_latest_episode_url }}"
                   class="link"
                   aria-label="Latest Episode"
                   title="Latest Episode">
                    Latest episode
                    {% include "_date.html" with value=podcast.pub_date title="Release Date" %}
                </a>
            </div>
        </div>
    </div>
    {% if podcast.funding_url %}
        <div class="flex-wrap font-semibold">
            <a href="{{ podcast.funding_url }}"
               rel="noopener nofollow"
               target="_blank">{{ podcast.funding_text|default:'Support this podcast' }}</a>
        </div>
    {% endif %}
    {% cache 600 podcast-categories podcast.pk %}
    {% with categories=podcast.categories.all %}
        {% if categories %}
            <div class="flex flex-wrap items-center leading-loose max-w-prose space-x-2 sm:space-x-3">
                {% for category in categories %}
                    <a class="inline-flex items-center link"
                       aria-label="{{ category.name }} Podcasts"
                       title="{{ category.name }} Podcasts"
                       href="{{ category.get_absolute_url }}">
                        {% heroicon_mini "tag" class="mr-2" %}
                        {{ category.name }}
                    </a>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
{% endcache %}
{% markdown podcast.description %}
</article>
{% endblock podcast_content %}

templates/podcasts/detail_base.html
{% extends "base.html" %}
{% load cache heroicons %}
{% block title %}
    | {{ podcast.cleaned_title }}
{% endblock title %}
{% block content %}
    <header class="pb-3 mb-6 border-b space-y-6">
        <h1 class="flex items-center justify-center text-lg font-bold text-center sm:justify-start lg:text-xl xl:text-2xl sm:text-start">
            {{ podcast.cleaned_title }}
        </h1>
        {% cache 600 podcast-detail-header request.get_full_path %}
        {% with num_episodes=podcast.episodes.count has_similar=podcast.recommendations.exists %}
            {% if num_episodes or has_similar or podcast.private %}
                <nav class="flex items-center justify-center mb-3 sm:justify-start">
                    <ul class="flex items-center space-x-6">
                        {% active_link podcast.get_detail_url as link %}
                        <li>
                            <a class="{{ link.css }}"
                               href="{{ link.url }}"
                               {% if link.active %}aria-current="page"{% endif %}
                               aria-label="{{ podcast.cleaned_title }} | About"
                               title="{{ podcast.cleaned_title }} | About">About</a>
                        </li>
                        {% if num_episodes %}
                            {% active_link podcast.get_episodes_url as link %}
                            <li>
                                <a class="{{ link.css }}"
                                   href="{{ link.url }}"
                                   {% if link.active %}aria-current="page"{% endif %}
                                   aria-label="{{ podcast.cleaned_title }} | Episodes"
                                   title="{{ podcast.cleaned_title }} | Episodes">Episodes ({{ num_episodes }})</a>
                            </li>
                        {% endif %}
                        {% if podcast.private %}
                            <li>
                                <a class="flex items-center link"
                                   href="{% url "podcasts:private_feeds" %}">
                                    {% heroicon_mini "lock-closed" class="mr-2" %}
                                    <span>Private Feed</span>
                                </a>
                            </li>
                        {% elif has_similar %}
                            {% active_link podcast.get_similar_url as link %}
                            <li>
                                <a class="{{ link.css }}"
                                   href="{{ link.url }}"
                                   {% if link.active %}aria-current="page"{% endif %}
                                   aria-label="{{ podcast.cleaned_title }} | Similar"
                                   title="{{ podcast.cleaned_title }} | Similar">Similar</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        {% endwith %}
    {% endcache %}
</header>
{% block podcast_content %}
{% endblock podcast_content %}
{% endblock content %}

templates/podcasts/index.html
{% extends "base.html" %}
{% load partials %}
{% block title %}
    | Podcasts
    {% if has_subscriptions %}| {{ promoted|yesno:"Promotions,Subscriptions" }}{% endif %}
{% endblock title %}
{% block content %}
    <header class="pb-3 mb-6 border-b space-y-3 sm:space-y-6">
        {% if has_subscriptions %}
            <h1 class="flex items-center justify-center text-lg font-bold sm:justify-start md:text-xl xl:text-2xl">
                Podcasts: {{ promoted|yesno:"Promotions,Subscriptions" }}
            </h1>
            <nav>
                <ul class="items-center justify-between sm:flex space-y-3 sm:space-y-0">
                    <li class="flex items-center justify-center sm:justify-start">
                        {% url 'podcasts:index' as index_url %}
                        {% if promoted %}
                            <a href="{{ index_url }}" class="link">Subscriptions</a>
                        {% else %}
                            <a href="{{ index_url }}?promoted=true" class="link">Promotions</a>
                        {% endif %}
                    </li>
                    <li class="flex items-center justify-center sm:justify-end space-x-3">
                        {% include "_search_form.html" with placeholder="Search: Podcasts" %}
                    </li>
                </ul>
            </nav>
        {% else %}
            <div class="items-center justify-between sm:flex space-y-6 sm:space-y-0">
                <h1 class="flex items-center justify-center text-lg font-bold sm:justify-start md:text-xl xl:text-2xl">Podcasts</h1>
                <nav class="flex items-center justify-center sm:justify-end space-x-3">
                    {% include "_search_form.html" with placeholder="Search: Podcasts" %}
                </nav>
            </div>
        {% endif %}
    </header>
    {% partialdef pagination inline=True %}
    {% include "podcasts/_podcasts.html" %}
{% endpartialdef pagination %}
{% endblock content %}

templates/podcasts/private_feed_form.html
{% extends "base.html" %}
{% load heroicons partials %}
{% block title %}
    {{ block.super }} | Private Feeds | Add Feed
{% endblock title %}
{% block content %}
    <header class="pb-3 mb-6 border-b space-y-3 sm:space-y-0 sm:flex items-center justify-between">
        <h1 class="flex items-center justify-center text-lg font-bold sm:justify-start lg:text-xl xl:text-2xl">
            Add Private Feed
        </h1>
        <nav>
            <ul class="items-center justify-between sm:flex space-y-3 sm:space-y-0">
                <li class="flex items-center justify-center mb-3 sm:justify-start sm:mb-0">
                    <a href="{% url "podcasts:private_feeds" %}" class="link">Private Feeds</a>
                </li>
            </ul>
        </nav>
    </header>
    {% partialdef form inline=True %}
    <form method="post"
          action="{{ request.path }}"
          class="space-y-3"
          id="private-feed-form"
          hx-post="{{ request.path }}"
          hx-target="this"
          hx-swap="outerHTML">
        {% csrf_token %}
        {{ form }}
        <div>
            <button class="inline-flex items-center btn btn-primary">
                {% heroicon_mini "plus" class="mr-2" %}
                Add Feed
            </button>
        </div>
    </form>
{% endpartialdef form %}
{% endblock content %}

templates/podcasts/private_feeds.html
{% extends "base.html" %}
{% load heroicons partials %}
{% block title %}
    {{ block.super }} | Private Feeds
{% endblock title %}
{% block content %}
    <header class="pb-3 mb-6 border-b space-y-3 {% if not page_obj.has_other_pages %}sm:space-y-0 sm:flex items-center justify-between{% endif %}">
        <h1 class="flex items-center justify-center text-lg font-bold sm:justify-start md:text-xl xl:text-2xl">
            Private Feeds
        </h1>
        <nav>
            <ul class="items-center justify-between sm:flex space-y-3 sm:space-y-0 sm:space-x-3">
                <li class="flex items-center justify-center mb-3 sm:justify-start sm:mb-0">
                    {% if request.search %}
                        <a href="{% url 'podcasts:search_podcasts' %}?{{ request.search.qs }}"
                           class="link">Search All Podcasts</a>
                    {% else %}
                        <a href="{% url "podcasts:add_private_feed" %}"
                           class="inline-flex items-center btn btn-default">
                            {% heroicon_mini "plus" class="mr-2" %}
                            Add Private Feed
                        </a>
                    {% endif %}
                </li>
                {% if request.search or page_obj.has_other_pages %}
                    <li class="flex items-center justify-center sm:justify-end">
                        {% include "_search_form.html" with placeholder="Search: Private Feeds" %}
                    </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% partialdef pagination inline=True %}
    {% include "podcasts/_podcasts.html" %}
{% endpartialdef pagination %}
{% endblock content %}

templates/podcasts/search.html
{% extends "search_base.html" %}
{% load cache partials %}
{% block title %}
    | Search | Podcasts
{% endblock title %}
{% block search_content %}
    {% partialdef pagination inline=True %}
    {% cache 600 search-podcasts request.get_full_path %}
    {% include "podcasts/_podcasts.html" %}
{% endcache %}
{% endpartialdef pagination %}
{% endblock search_content %}